/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

/**
 *
 * @author user
 */
public class Admin extends javax.swing.JPanel {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenu = new javax.swing.JButton();
        btnInventari = new javax.swing.JButton();
        btnTable = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        btnEndDay = new javax.swing.JButton();
        jLabel_BlueBackgroud = new javax.swing.JLabel();
        jLabel_Admin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenu.setText("Menú");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 80));

        btnInventari.setText("Inventario");
        btnInventari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventariActionPerformed(evt);
            }
        });
        add(btnInventari, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 80));

        btnTable.setText("Mesas");
        btnTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableActionPerformed(evt);
            }
        });
        add(btnTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 130, 80));

        btnReport.setText("Reporte");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        add(btnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 130, 80));

        btnRegister.setText("Regitrar Usuario");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 130, -1));

        btnEndDay.setText("Finalizar Día");
        btnEndDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndDayActionPerformed(evt);
            }
        });
        add(btnEndDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 130, 30));

        jLabel_BlueBackgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue Backgroud.jpg"))); // NOI18N
        jLabel_BlueBackgroud.setText("jLabel1");
        add(jLabel_BlueBackgroud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 500));

        jLabel_Admin.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel_Admin.setForeground(new java.awt.Color(102, 102, 102));
        jLabel_Admin.setText("Administrador");
        add(jLabel_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 640, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventariActionPerformed

    private void btnTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTableActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnEndDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEndDayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEndDay;
    private javax.swing.JButton btnInventari;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Admin;
    private javax.swing.JLabel jLabel_BlueBackgroud;
    // End of variables declaration//GEN-END:variables
}
