package Interface;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pos.Logic;

/**
 * Class that represents the Bartender window in the application.
 *
 * @author Diego Herrera López
 * @author Kevin Sibaja Granados
 * @author Yordany Navarro Hernandez
 * @author Tiffany Hernández Rodriguez
 * @author Jonathan Alfaro Herrera
 */
public class FRMBartender extends javax.swing.JFrame {

    static String table = "";
    Logic logic;

    /**
     * Constructor of the FRMBartender class. Create a new instance of the Logic
     * class and call the initComponents() method to initialize the window
     * components. The readStatus() method is called to load the statuses of the
     * tables. The method loadChefBartView(jtBartTables) is called, to which the
     * table "jtBartTables" is passed as a parameter to show the tables with
     * orders.
     */
    public FRMBartender() {
        initComponents();
        logic = new Logic();
        logic.readStatus();
        logic.loadChefBartView(jtBartTables);
        this.setExtendedState(this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtBartTables = new javax.swing.JTable();
        btnDetailsTableBart = new javax.swing.JButton();
        btnLockOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtBartOrder = new javax.swing.JTable();
        btnOrderDone = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmHelpBart = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(240);

        jPanel2.setBackground(new java.awt.Color(65, 128, 171));

        jtBartTables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Mesas"
            }
        ));
        jScrollPane2.setViewportView(jtBartTables);

        btnDetailsTableBart.setBackground(new java.awt.Color(240, 236, 201));
        btnDetailsTableBart.setText("Ver detalles");
        btnDetailsTableBart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsTableBartActionPerformed(evt);
            }
        });

        btnLockOut.setBackground(new java.awt.Color(153, 153, 153));
        btnLockOut.setForeground(new java.awt.Color(0, 0, 0));
        btnLockOut.setText("Cerrar sesion");
        btnLockOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLockOutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bartender");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bartender.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnDetailsTableBart))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(7, Short.MAX_VALUE))
            .addComponent(btnLockOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDetailsTableBart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnLockOut, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        jPanel3.setBackground(new java.awt.Color(189, 209, 222));

        jtBartOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Cantidad", "Comentario", "Estado"
            }
        ));
        jScrollPane3.setViewportView(jtBartOrder);

        btnOrderDone.setBackground(new java.awt.Color(69, 147, 108));
        btnOrderDone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check.png"))); // NOI18N
        btnOrderDone.setText("Listo");
        btnOrderDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderDoneActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel2.setText("Bebidas en proceso");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOrderDone)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel2)
                .addContainerGap(226, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOrderDone)
                .addGap(116, 116, 116))
        );

        jSplitPane1.setRightComponent(jPanel3);

        jmHelpBart.setText("Ayuda");
        jmHelpBart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmHelpBartMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmHelpBart);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method that is executed when an action is performed on the
     * "btnDetailsTableBart" button.A variable of type int is created to which
     * the number of the selected row in the table is assigned. The value of the
     * table containing tables in the selected row and column "0" is obtained
     * and assigned to the variable table . loadTableChefBart(table) is called
     * to load the txt of the selected table and then
     * loadListToTableBart(jtBartOrder) is called to display the data in the
     * "jtBartOrder" table
     *
     * @param evt table detail button
     */
    private void btnDetailsTableBartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsTableBartActionPerformed
        try {
            int selectedRow = jtBartTables.getSelectedRow();

            table = jtBartTables.getValueAt(selectedRow, 0).toString();

            logic.listTableChefBart.clear();

            logic.loadTableChefBart(table);
            logic.loadListToTableBart(jtBartOrder);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ninguna mesa seleccionada");
        }
    }//GEN-LAST:event_btnDetailsTableBartActionPerformed
    /**
     * Method that is executed when an action is performed on the "btnLockOut"
     * button. Call the "lockOut()" method of the "logic" class instance. Close
     * the current window "dispose()"
     *
     * @param evt close frame button
     */
    private void btnLockOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLockOutActionPerformed
        logic.lockOut();
        dispose();
    }//GEN-LAST:event_btnLockOutActionPerformed
    /**
     * Method that is executed when an action is performed on the "btnOrderDone"
     * button. A variable of type int is created to which the number of the
     * selected row in the table is assigned. Then if a row is selected a String
     * variable "productName" is assigned to what it has the selected row in
     * column 0. The method "donePlate(productName)" is called. to assign ready
     * or waiting and finally it is written again in the txt with the new status
     * in the order and it is downloaded again
     *
     * @param evt order button ready
     */
    private void btnOrderDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderDoneActionPerformed
        int selectedRow = jtBartOrder.getSelectedRow();

        if (selectedRow != -1) {
            String productName = jtBartOrder.getValueAt(selectedRow, 0).toString();
            logic.donePlate(productName);

            logic.saveOrderChefBart(table.replaceAll("mesa", ""));
            logic.loadListToTableBart(jtBartOrder);

        } else {
            JOptionPane.showMessageDialog(null, "Ningun pedido seleccionado");
        }
    }//GEN-LAST:event_btnOrderDoneActionPerformed
    /**
     * Method that is executed when an action is performed in "jmHelpBart" of
     * the ToolBar. A dialog of type "FRMDialogHelp" is created to which a
     * variable of type String with the name of the frame will be passed as a
     * parameter. The created dialog will be placed in the center of the screen
     * and will be set visible
     *
     * @param evt bartender help button
     */
    private void jmHelpBartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmHelpBartMouseClicked
        try {
            String nameFrame = "Bartender";
            FRMDialogHelp dialogHelp = new FRMDialogHelp(null, true, nameFrame);
            dialogHelp.setLocationRelativeTo(null);
            dialogHelp.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(FRMBartender.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmHelpBartMouseClicked

    /**
     * Java application entry point.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMBartender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMBartender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMBartender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMBartender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FRMBartender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetailsTableBart;
    private javax.swing.JButton btnLockOut;
    private javax.swing.JButton btnOrderDone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JMenu jmHelpBart;
    private javax.swing.JTable jtBartOrder;
    private javax.swing.JTable jtBartTables;
    // End of variables declaration//GEN-END:variables
}
