package Interface;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pos.Logic;

/**
 * Class that represents the Chef window in the application.
 *
 * @author Diego Herrera López
 * @author Kevin Sibaja Granados
 * @author Yordany Navarro Hernandez
 * @author Tiffany Hernández Rodriguez
 * @author Jonathan Alfaro Herrera
 */
public class FRMChef extends javax.swing.JFrame {

    static String table = "";
    Logic logic;

    /**
     * Constructor of the FRMChef class. Create a new instance of the Logic
     * class and call the initComponents() method to initialize the window
     * components. The readStatus() method is called to load the statuses of the
     * tables. The method loadChefBartView(jtChefTables) is called, to which the
     * table "jtChefTables" is passed as a parameter to show the tables with
     * orders.
     */
    public FRMChef() {
        initComponents();
        logic = new Logic();
        logic.readStatus();
        logic.loadChefBartView(jtChefTables);
        this.setExtendedState(this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtChefTables = new javax.swing.JTable();
        btnDetailsTable = new javax.swing.JButton();
        btnLockOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtChefOrder = new javax.swing.JTable();
        btnOrderDone = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmHelpChef = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane2.setDividerLocation(250);

        jPanel4.setBackground(new java.awt.Color(65, 128, 171));

        jtChefTables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Mesas"
            }
        ));
        jScrollPane2.setViewportView(jtChefTables);

        btnDetailsTable.setBackground(new java.awt.Color(240, 236, 201));
        btnDetailsTable.setForeground(new java.awt.Color(0, 0, 0));
        btnDetailsTable.setText("Ver detalles");
        btnDetailsTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsTableActionPerformed(evt);
            }
        });

        btnLockOut.setBackground(new java.awt.Color(153, 153, 153));
        btnLockOut.setForeground(new java.awt.Color(0, 0, 0));
        btnLockOut.setText("Cerrar sesión");
        btnLockOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLockOutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Chef");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chef.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnDetailsTable))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnLockOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDetailsTable)
                .addGap(68, 68, 68)
                .addComponent(btnLockOut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jSplitPane2.setLeftComponent(jPanel4);

        jPanel5.setBackground(new java.awt.Color(189, 209, 222));

        jtChefOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Cantidad", "Comentario", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtChefOrder);

        btnOrderDone.setBackground(new java.awt.Color(69, 147, 108));
        btnOrderDone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check.png"))); // NOI18N
        btnOrderDone.setText("Listo");
        btnOrderDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderDoneActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Platillos en Proceso");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOrderDone))
                    .addComponent(jScrollPane3))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(181, 181, 181))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrderDone)
                .addGap(157, 157, 157))
        );

        jSplitPane2.setRightComponent(jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jmHelpChef.setText("Ayuda");
        jmHelpChef.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmHelpChefMouseClicked(evt);
            }
        });
        jMenuBar2.add(jmHelpChef);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method that is executed when an action is performed on the
     * "btnDetailsTable" button.A variable of type int is created to which the
     * number of the selected row in the table is assigned. The value of the
     * table containing tables in the selected row and column "0" is obtained
     * and assigned to the variable table . loadTableChefBart(table) is called
     * to load the txt of the selected table and then
     * loadListToTableBart(jtChefOrder) is called to display the data in the
     * "jtBartOrder" table
     *
     * @param evt table details button
     */
    private void btnDetailsTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsTableActionPerformed

        try {
            int selectedRow = jtChefTables.getSelectedRow();

            table = jtChefTables.getValueAt(selectedRow, 0).toString();

            logic.listTableChefBart.clear();

            logic.loadTableChefBart(table);

            logic.loadListToTableChef(jtChefOrder);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ninguna mesa seleccionada");
        }

    }//GEN-LAST:event_btnDetailsTableActionPerformed
    /**
     * Method that is executed when an action is performed on the "btnLockOut"
     * button. Call the "lockOut()" method of the "logic" class instance. Close
     * the current window "dispose()"
     *
     * @param evt close frame button
     */
    private void btnLockOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLockOutActionPerformed
        logic.lockOut();
        dispose();
    }//GEN-LAST:event_btnLockOutActionPerformed
    /**
     * Method that is executed when an action is performed on the "btnOrderDone"
     * button. A variable of type int is created to which the number of the
     * selected row in the table is assigned. Then if a row is selected a String
     * variable "productName" is assigned to what it has the selected row in
     * column 0. The method "donePlate(productName)" is called. to assign ready
     * or waiting and finally it is written again in the txt with the new status
     * in the order and it is downloaded again
     *
     * @param evt order button ready
     */
    private void btnOrderDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderDoneActionPerformed
        int selectedRow = jtChefOrder.getSelectedRow();

        if (selectedRow != -1) {
            String productName = jtChefOrder.getValueAt(selectedRow, 0).toString();
            logic.donePlate(productName);

            logic.saveOrderChefBart(table.replaceAll("mesa", ""));
            logic.loadListToTableChef(jtChefOrder);

        } else {
            JOptionPane.showMessageDialog(null, "Ningun pedido seleccionado");
        }
    }//GEN-LAST:event_btnOrderDoneActionPerformed
    /**
     * * Method that is executed when an action is performed in "jmHelpBart" of
     * the ToolBar. A dialog of type "FRMDialogHelp" is created to which a
     * variable of type String with the name of the frame will be passed as a
     * parameter. The created dialog will be placed in the center of the screen
     * and will be set visible
     *
     * @param evt The mouse event generated by the menu item.
     */
    private void jmHelpChefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmHelpChefMouseClicked
        try {
            String nameFrame = "Chef";
            FRMDialogHelp dialogHelp = new FRMDialogHelp(null, true, nameFrame);
            dialogHelp.setLocationRelativeTo(null);
            dialogHelp.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(FRMChef.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmHelpChefMouseClicked

    /**
     * Java application entry point.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FRMChef().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetailsTable;
    private javax.swing.JButton btnLockOut;
    private javax.swing.JButton btnOrderDone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JMenu jmHelpChef;
    private javax.swing.JTable jtChefOrder;
    private javax.swing.JTable jtChefTables;
    // End of variables declaration//GEN-END:variables
}
