/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interface;

import classes.Product;
import java.awt.BorderLayout;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.LinkedList;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author Hp EliteBook
 */
public class JIFReport extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFReport
     */
    public JIFReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpReport = new javax.swing.JPanel();
        btnAddReport = new javax.swing.JButton();

        btnAddReport.setText("Ver button");
        btnAddReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpReportLayout = new javax.swing.GroupLayout(jpReport);
        jpReport.setLayout(jpReportLayout);
        jpReportLayout.setHorizontalGroup(
            jpReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReportLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnAddReport, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(656, Short.MAX_VALUE))
        );
        jpReportLayout.setVerticalGroup(
            jpReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpReportLayout.createSequentialGroup()
                .addContainerGap(379, Short.MAX_VALUE)
                .addComponent(btnAddReport, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddReportActionPerformed
          try {
            String reportPath = "C:\\Users\\Hp EliteBook\\JaspersoftWorkspace\\MyReports\\reportePos.jrxml";
            LinkedList<Product> listReport = new LinkedList<>();

            
            String filePath = "reporte.txt";
            try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
                String line;
                while ((line = br.readLine()) != null) {
                    String[] data = line.split(",");
                    String productName = data[0];
                    int quantity = Integer.parseInt(data[1]);

                    Product product = new Product(productName, quantity);
                    listReport.add(product);
                }
            }

          
            JasperReport report = (JasperReport) net.sf.jasperreports.engine.JasperCompileManager.compileReport(reportPath);
            JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(listReport);
            JasperPrint print = JasperFillManager.fillReport(report, null, dataSource);

            JRViewer viewer = new JRViewer(print);
            
            jpReport.add(viewer, BorderLayout.CENTER);
            getContentPane().add(jpReport);

        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }//GEN-LAST:event_btnAddReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddReport;
    private javax.swing.JPanel jpReport;
    // End of variables declaration//GEN-END:variables
}
